In [11]:
import numpy as np
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
import numpy as np
zero_ar = np.zeros(10)
zero_ar

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
import numpy as np
zero_ar_int = np.zeros(10, dtype=int)
zero_ar_int


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
import numpy as np
np_fill = np.full(10, 69)
np_fill

array([69, 69, 69, 69, 69, 69, 69, 69, 69, 69])

In [15]:
import numpy as np
ranged_array = np.arange(10, 69, 2)
ranged_array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68])

2D ARRAYS

In [24]:
import numpy as np
random2D_array = np.random.rand(4, 3)
random2D_array


array([[0.97527285, 0.75411758, 0.31518581],
       [0.49620752, 0.22817999, 0.48661594],
       [0.16965144, 0.10875818, 0.76157347],
       [0.01636403, 0.84922401, 0.18441303]])

3D ARRAYS


In [27]:
import numpy as np
random3D_array = np.random.rand(4, 3, 2)
random3D_array

array([[[0.84969252, 0.29347659],
        [0.99018769, 0.04091711],
        [0.90714934, 0.13248933]],

       [[0.09739925, 0.78822384],
        [0.88712776, 0.49926052],
        [0.61676785, 0.77410401]],

       [[0.25364137, 0.56337207],
        [0.29750265, 0.57524659],
        [0.14367781, 0.20443742]],

       [[0.14523116, 0.80996038],
        [0.92839827, 0.34328212],
        [0.84072115, 0.30074183]]])

ARRAY INDEX

array [ start : end : jump ]

In [32]:
ran = range(1, 11)
np_10Num = np.array(ran)
np_10Num
#np_10Num[3]
#np_10Num[-1]
#np_10Num[:4] 
#np_10Num[ : : 2] jumps by 2
#np_10Num[1 : 9 : 2]starts at 1, finishes at 9, jumps by 2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2D arrays index

In [44]:
#random2D_array[2,] #1st column
#random2D_array[:, 2] #2nd column
random2D_array[4:2, 2:3] #1st column



array([], shape=(0, 1), dtype=float64)

basic operators

In [45]:
np.arange(1, 65)
reordered = np.arange(1, 65).reshape(8, 8)
reordered

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [48]:
arr1 = np.random.randint(10, size = 6)
arr2 = np.random.randint(10, size = 9)

arr_conc = np.concatenate([arr1, arr2])
arr_conc


array([1, 8, 1, 4, 0, 1, 2, 8, 0, 7, 1, 0, 4, 0, 0])

In [49]:
arr1.sum() 

15

In [50]:
arr1.max() 

8

In [51]:
arr1.mean() 

2.5

In [53]:
np.median(arr1) 

1.0

In [54]:
arr1.std() 

2.753785273643051

In [55]:
arr1.var() 

7.583333333333333